ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

alias em=ember
alias ems="em s"
alias be="bundle exec"
alias bower="noglob bower"
alias pdflatex="mkdir -p build; pdflatex -output-directory build"
alias vi=vim
alias rjw="rake jobs:work"

DISABLE_CORRECTION="true"

DISABLE_AUTO_UPDATE="true" #Stop breaking my shit!

plugins=(docker git gem rails ruby heroku bundler brew pass npm)

source $ZSH/oh-my-zsh.sh
[ -f dnvm.sh ] &&  source dnvm.sh

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

export INC=$INC:~/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/

export PATH=$PATH:~/perl5/perlbrew/bin/
export PATH=$PATH:/usr/local/share/npm/bin
export PATH=$PATH:~/SSHcoms

#PATH=$PATH:/opt/local/bin
PATH=$PATH:~/bin

NODES+=(/usr/local/Cellar/node/*)

[ -f dinghy ] && eval "$(dinghy shellinit)"

export MAGICK_HOME="/opt/ImageMagick-6.9.1"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"
export DISPLAY=:0

export PATH="$MAGICK_HOME/bin:$PATH"


export EDITOR=emacs
export PAPERTRAIL_API_TOKEN='HM3R8IJe0xujQDiTY'

#THIS MUST BE AT THE END OF THE FILE FOR JENV TO WORK!!!
[[ -s "/Users/sre/.jenv/bin/jenv-init.sh" ]] && source "/Users/sre/.jenv/bin/jenv-init.sh" && source "/Users/sre/.jenv/commands/completion.sh"
